language: python

python:
  - '3.7-dev'

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/moviesdb
    - secure: AYYszRMqAY/kohN+HoQEPUWvH/wbINnPawajmEjVGheO45gWB3fIh96jkejqFp0bDJGcvTc/pXgfYkhDnYeC7JALp2RyO8/KWI0p2i7DkZCyHJEqasY2egSA+o5pZSDT6mgZvl6agAMfHFAyasx0bLnnpRkwGcYHAG3pM7jsVk7IRwBZDKr4GuvMYK67iv8C60PPNbsuEAH6GQ3idfsdo1Gfx6EVPHva3EzVWIYYKAlQx+YZ88YGj6qeee16RKnB89xrMNO/9kpbmt7aZvsCXvcRNPMfrYkS0FC6otCE2j21Hc34OXSlgBG1oRr006cf2ztpSO7gVKS27DJAalYOq+ut4i+H3I+akSq6q9HY4703dZUWJxTxNC/z1RXBYEAbzmKs02lCChSJHbKK/g4UTlukThgi8Dk3za58WIC4r2hRX4j9maIp5oix2v6p+PUHP5Hwr36+n/YmdwjTmJjqVa8HGJGV3ZNIxhMbYLS8zAZj8KDYMLq9SDPADZu1Oc14HWTx4XuySlfKTLnhKXR6LcNtVak4koeb62O2xO54SmcsFefiLPcQlDkyFo3OIliTgnl7jzPAgyxzguOBqSLa4vPg9xDfh3NrY8H6BX2GqYha1QUXg/ULxOC86FY8kfcNiBpcNnQ+F5YGU8EWG65tToUkGRKAdTUn76C0UJukZP4=

addons:
  postgresql: "9.6"

before_install:
  - psql -c 'create database moviesdb;' -U postgres

install:
  - pip install -r requirements-test.txt
  - cd src
  - python manage.py migrate

script:
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success: coveralls
